---
name: ((deployment_name))

releases:
- name: uaa
  version: ((uaa_version))
  sha1: ((uaa_sha1))
  url: https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=((uaa_version))  

instance_groups:
- name: uaa
  instances: 1
  azs: [z1]
  networks: [{name: ((network_name))}]
  stemcell: trusty
  vm_type: ((uaa_vm_type))
  jobs:
  - name: uaa
    release: uaa
    properties:
      uaa:
        url: "https://((uaa_host))"
        port: -1
        scim:
          users:
          - name: admin
            password: ((uaa-users-admin))
            groups:
              - scim.write
              - scim.read
              - bosh.admin
              - credhub.read
              - credhub.write
        clients:
          credhub_cli:
            override: true
            authorized-grant-types: password,refresh_token
            scope: credhub.read,credhub.write
            authorities: uaa.resource
            access-token-validity: 30
            refresh-token-validity: 3600
            secret: ""
          concourse_to_credhub:
            override: true
            authorized-grant-types: client_credentials
            scope: ""
            authorities: credhub.read,credhub.write
            access-token-validity: 30
            refresh-token-validity: 3600
            secret: ((concourse_to_credhub_secret))            
        admin: {client_secret: ((uaa-admin))}
        login: {client_secret: ((uaa-login))}
        zones: {internal: {hostnames: []}}
        sslCertificate: ((uaa-tls.certificate))
        sslPrivateKey: ((uaa-tls.private_key))
        jwt:
          revocable: true
          policy:
            active_key_id: key-1
            keys:
              key-1:
                signingKey: ((uaa-jwt.private_key))
      uaadb:
        address: ((uaa_database_host))
        port: ((uaa_database_port))
        db_scheme: postgresql
        # This must currently be false unless the CA of the DB is added to the BOSH CA trust store
        tls_enabled: false 
        databases:
        - tag: uaa
          name: uaa
        roles:
        - tag: admin
          name: ((uaa_database_username))
          password: ((uaa_database_password))
      login:
        saml:
          serviceProviderCertificate: ((uaa-tls.certificate))
          serviceProviderKey: ((uaa-tls.private_key))
          serviceProviderKeyPassword: ""

variables:
- name: uaa-ca
  type: certificate
  options:
    is_ca: true
    common_name: UAA CA
- name: uaa-tls
  type: certificate
  options:
    ca: uaa-ca
    common_name: ((uaa_host))
- name: uaa-jwt
  type: rsa
  options:
    key_length: 4096
- name: uaa-users-admin
  type: password
- name: uaa-admin
  type: password
- name: uaa-login
  type: password
- name: concourse_to_credhub_secret
  type: password  

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000